apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-deployment
  namespace: dev

spec:
  repliceas: 2
  selector:
    matchLabels:
      app: dev-pod 
  template:
    metadata:
      labels:
        app: dev-pod 
    spec:
      containers:
      - name: dev-container
        image: wil42/playground:v2
        ports:
        - containerPort: 8888
